#!/usr/bin/env python3
"""
Daily Healthcare-AI digest generator
1) PubMed 최신 5편
2) GitHub 트렌딩 AI·헬스 레포 5개
결과 → data/YYYY-MM-DD.md
"""
import datetime, pathlib, requests, textwrap

TODAY = datetime.date.today().isoformat()
DST   = pathlib.Path("data") / f"{TODAY}.md"
DST.parent.mkdir(exist_ok=True)

def pubmed_links(q, n=5):
    resp = requests.get(
        "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi",
        params={"db":"pubmed","term":q,"retmax":n,"sort":"pub+date","retmode":"json"},
        timeout=30,
    )
    ids = resp.json()["esearchresult"]["idlist"]
    return [f"- PMID {id}: <https://pubmed.ncbi.nlm.nih.gov/{id}/>" for id in ids]

def github_trending(topic="ai", n=5):
    hdr  = {"Accept":"application/vnd.github+json"}
    resp = requests.get(
        f"https://api.github.com/search/repositories",
        params={"q":f"topic:{topic} stars:>1000","sort":"updated","order":"desc","per_page":n},
        headers=hdr, timeout=30,
    )
    return [f"- {r['full_name']}: ⭐ {r['stargazers_count']} {r['html_url']}"
            for r in resp.json()["items"]]

content = textwrap.dedent(f"""\
    # Daily Healthcare-AI Digest – {TODAY}

    ## 📚 PubMed fresh papers
    {'\\n'.join(pubmed_links('healthcare artificial intelligence agent'))}

    ## 🚀 GitHub trending (AI / healthcare)
    {'\\n'.join(github_trending())}

    _Auto-generated by daily_update.py_
    """)

DST.write_text(content, encoding="utf-8")
print(f"Wrote {DST}")
